/**
 * SpecCom Client Presentation — Sample Workflow Data
 *
 * Fake but believable telecom field operations data.
 * Used only in presentation.html — never touches real Supabase records.
 */

window.PRESENTATION_CONFIG = {
  clients: {
    "ks-electric": {
      clientSlug: "ks-electric",
      clientName: "K&S Electric",
      industryLabel: "Telecom / Utility Field Operations",
      presentationTitle: "SpecCom Field Operations Presentation",
      marketFocus: ["OSP", "Splicing", "I&R", "Drop Crew", "Warehouse", "Billing"],
      logoMode: "text",
      accentColor: "#378ADD",
    },
  },
  defaultClient: {
    clientSlug: "default",
    clientName: "Telecom Operations Team",
    industryLabel: "Field Operations",
    presentationTitle: "SpecCom Field Operations Presentation",
    marketFocus: ["OSP", "Splicing", "I&R", "Drop Crew", "Warehouse", "Billing"],
    logoMode: "text",
    accentColor: "#378ADD",
  },
};

window.PRESENTATION_KPIS = {
  activeJobs: 14,
  blockedJobs: 2,
  crewsWorking: 8,
  photosCaptured: 347,
  invoicesReadyForReview: 6,
  materialAlerts: 3,
  sitesDocumented: 91,
  totalProjects: 6,
};

window.PRESENTATION_PROJECTS = [
  {
    id: "proj-001",
    name: "Ruidoso Node 54 Fiber Closeout",
    type: "OSP / Splicing",
    location: "Ruidoso, NM — Node 54 Area",
    status: "In Review",
    statusColor: "#D39A44",
    description: "Splice verification, redline cleanup, GPS/photo proof, and closeout package review.",
    assignedCrew: "OSP Splice Crew — Patrick H.",
    taskCount: 18,
    photoCount: 94,
    noteCount: 12,
    materialCount: 0,
    invoiceRef: "TDS-NODE54-026",
    redlineMarkers: 7,
    tags: ["Closeout", "Splicing", "Redline"],
    milestones: [
      { label: "Field splicing complete", done: true },
      { label: "GPS/photo proof uploaded", done: true },
      { label: "Redlines updated", done: true },
      { label: "Closeout package submitted", done: false },
      { label: "Final billing approved", done: false },
    ],
  },
  {
    id: "proj-002",
    name: "Enterprise FTTH Expansion",
    type: "Fiber Build",
    location: "Enterprise, AL — Zone 3 Extension",
    status: "Active",
    statusColor: "#1D9E75",
    description: "Mainline fiber extension, splice points, material tracking, and crew documentation.",
    assignedCrew: "OSP Build Crew — Jake M., Derrick T.",
    taskCount: 31,
    photoCount: 128,
    noteCount: 21,
    materialCount: 64,
    invoiceRef: null,
    redlineMarkers: 11,
    tags: ["FTTH", "OSP", "Active Build"],
    milestones: [
      { label: "Route staking approved", done: true },
      { label: "Mainline fiber pulled", done: true },
      { label: "Splice points documented", done: false },
      { label: "Customer drop schedule confirmed", done: false },
      { label: "Final acceptance walk", done: false },
    ],
  },
  {
    id: "proj-003",
    name: "Daleville Drop Completion Batch",
    type: "Drop Crew / Install Support",
    location: "Daleville, AL — Multiple Addresses",
    status: "Active",
    statusColor: "#1D9E75",
    description: "Customer drop completions, address notes, proof photos, and completion status.",
    assignedCrew: "I&R Drop Crew — Brandon S., Kyle W.",
    taskCount: 44,
    photoCount: 67,
    noteCount: 29,
    materialCount: 22,
    invoiceRef: "DALEVILLE-BATCH-03",
    redlineMarkers: 0,
    tags: ["Drop Crew", "I&R", "Installs"],
    milestones: [
      { label: "Address list imported", done: true },
      { label: "Crew assignments confirmed", done: true },
      { label: "31 drops completed", done: true },
      { label: "13 remaining scheduled", done: false },
      { label: "Batch billing submitted", done: false },
    ],
  },
  {
    id: "proj-004",
    name: "Ozark Cabinet Turnup Prep",
    type: "Network / Cabinet",
    location: "Ozark, AL — Cabinet OZK-14",
    status: "Pending Materials",
    statusColor: "#D39A44",
    description: "Cabinet prep, fiber jumpers, labeling, material checks, and readiness notes.",
    assignedCrew: "Network Crew — Chris B.",
    taskCount: 9,
    photoCount: 14,
    noteCount: 6,
    materialCount: 18,
    invoiceRef: null,
    redlineMarkers: 0,
    tags: ["Cabinet", "Network", "Pending"],
    milestones: [
      { label: "Cabinet site cleared", done: true },
      { label: "Fiber jumpers ordered", done: true },
      { label: "Materials received", done: false },
      { label: "Port labeling complete", done: false },
      { label: "Turnup test", done: false },
    ],
  },
  {
    id: "proj-005",
    name: "Warehouse Material Reconciliation",
    type: "Warehouse",
    location: "Main Warehouse — Bay 2",
    status: "Needs Review",
    statusColor: "#991b1b",
    description: "Compare expected materials against used materials and flag shortages.",
    assignedCrew: "Warehouse — Maria C.",
    taskCount: 7,
    photoCount: 4,
    noteCount: 8,
    materialCount: 112,
    invoiceRef: null,
    redlineMarkers: 0,
    tags: ["Warehouse", "Inventory", "Reconciliation"],
    milestones: [
      { label: "Material import from project records", done: true },
      { label: "Physical count scan complete", done: false },
      { label: "Shortage flags reviewed", done: false },
      { label: "Reorder submitted", done: false },
    ],
  },
  {
    id: "proj-006",
    name: "Invoice Verification Sample",
    type: "Billing / Office",
    location: "Office — Billing Review",
    status: "Ready for Review",
    statusColor: "#7F77DD",
    description: "Compare work performed, invoice lines, field photos, and project documentation.",
    assignedCrew: "Office — Billing Review",
    taskCount: 5,
    photoCount: 22,
    noteCount: 4,
    materialCount: 0,
    invoiceRef: "TDS-BATCH-FEB-2026",
    redlineMarkers: 0,
    tags: ["Billing", "Invoice", "Office"],
    milestones: [
      { label: "Invoice PDF imported", done: true },
      { label: "Field photo cross-reference", done: true },
      { label: "Line-item review", done: false },
      { label: "Approval submitted", done: false },
    ],
  },
];

window.PRESENTATION_UPLOAD_SAMPLES = [
  {
    id: "kmz-sample",
    label: "Import Sample KMZ",
    filename: "Ruidoso_Node54_Redlines.kmz",
    ext: "kmz",
    category: "Map / Redline File",
    destination: "Map Workspace → Import Route",
    action: "Import Map",
    icon: "📍",
    simulatedResult: {
      title: "Sample Import Preview",
      summary: "KMZ file parsed successfully.",
      details: [
        "14 route segments detected",
        "7 redline markers loaded",
        "3 splice point annotations",
        "KMZ layer ready for map overlay",
      ],
    },
  },
  {
    id: "pdf-sample",
    label: "Parse Sample Invoice",
    filename: "TDS_Invoice_2026-02-22.pdf",
    ext: "pdf",
    category: "Invoice / Billing Document",
    destination: "Invoice Workspace → Parse PDF",
    action: "Parse Invoice",
    icon: "📄",
    simulatedResult: {
      title: "Sample Import Preview",
      summary: "Invoice PDF parsed — 6 line items found.",
      details: [
        "Invoice #: TDS-2026-0222",
        "Total: $5,009.00",
        "6 billing line items extracted",
        "Field photo references matched: 4",
        "Ready for office review",
      ],
    },
  },
  {
    id: "photos-sample",
    label: "Upload Sample Photos",
    filename: "field_photos_batch_03.zip",
    ext: "zip",
    category: "Field Photo Batch",
    destination: "Photos Workspace → GPS-Tagged Upload",
    action: "Add Field Photos",
    icon: "📷",
    simulatedResult: {
      title: "Sample Import Preview",
      summary: "Photo batch processed — 12 photos with GPS metadata.",
      details: [
        "12 photos extracted from batch",
        "GPS coordinates found in 11 of 12",
        "Assigned to: Ruidoso Node 54",
        "Thumbnails ready for map view",
      ],
    },
  },
  {
    id: "excel-sample",
    label: "Import Materials",
    filename: "Material_List_Ozark_Cabinet.xlsx",
    ext: "xlsx",
    category: "Spreadsheet / Material Import",
    destination: "Warehouse / Project → Material Import",
    action: "Import Materials",
    icon: "📊",
    simulatedResult: {
      title: "Sample Import Preview",
      summary: "Spreadsheet parsed — 48 material line items.",
      details: [
        "48 material line items found",
        "Column mapping confirmed",
        "4 items flagged as low stock",
        "Ready for warehouse reconciliation",
      ],
    },
  },
];

window.PRESENTATION_WORKSPACES = [
  {
    key: "overview",
    title: "Operations Control",
    icon: `<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="2" y="3" width="16" height="13" rx="2"/><path d="M7 8h6M7 12h4"/></svg>`,
    accent: "#378ADD",
    summary: "Active jobs, crew status, blocked work, and daily operations overview.",
    chips: ["KPI Overview", "Blocked Jobs", "Crew Activity", "Daily Summary"],
    preview: "overview",
  },
  {
    key: "projects",
    title: "OSP / Splicing",
    icon: `<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M3 10h14"/><path d="M7 5l-4 5 4 5"/><path d="M13 5l4 5-4 5"/></svg>`,
    accent: "#7F77DD",
    summary: "Splice work, fiber counts, closures, redline map, and project billing.",
    chips: ["Fiber Map", "Closures", "Redlines", "Billing Codes"],
    preview: "projects",
  },
  {
    key: "technician",
    title: "I&R Technician",
    icon: `<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="10" cy="10" r="7"/><path d="M10 6v4l2.5 2.5"/></svg>`,
    accent: "#378ADD",
    summary: "Clock in, accept work orders, capture photos, complete service tickets.",
    chips: ["Clock In", "Work Orders", "Field Photos", "Complete"],
    preview: "technician",
  },
  {
    key: "drops",
    title: "Drop Crew",
    icon: `<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M10 3C7.24 3 5 5.24 5 8c0 4.5 5 9 5 9s5-4.5 5-9c0-2.76-2.24-5-5-5z"/><circle cx="10" cy="8" r="2"/></svg>`,
    accent: "#1D9E75",
    summary: "Drop completions, address notes, install proofs, and batch billing.",
    chips: ["Drop List", "Proof Photos", "Address Notes", "Batch Complete"],
    preview: "drops",
  },
  {
    key: "warehouse",
    title: "Warehouse",
    icon: `<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 17V8l8-5 8 5v9"/><path d="M8 17v-6h4v6"/></svg>`,
    accent: "#D39A44",
    summary: "Material search, barcode scan, inventory intake, and stock alerts.",
    chips: ["Catalog Search", "Scan", "Inventory", "Alerts"],
    preview: "warehouse",
  },
  {
    key: "billing",
    title: "Billing / Invoices",
    icon: `<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="4" y="2" width="12" height="16" rx="1.5"/><path d="M7.5 7h5M7.5 10h5M7.5 13h3.5"/></svg>`,
    accent: "#EE835D",
    summary: "Invoice review, approval, billing location comparison, and PDF import.",
    chips: ["Invoice Review", "Approve", "Reports", "PDF Import"],
    preview: "billing",
  },
  {
    key: "map",
    title: "Map / Redlines",
    icon: `<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="2" y="3" width="16" height="13" rx="1.5"/><path d="M2 8h16"/><circle cx="7" cy="12" r="1.5" fill="currentColor"/><circle cx="13" cy="12" r="1.5" fill="currentColor"/><path d="M7 12l6 0" stroke-dasharray="2 2"/></svg>`,
    accent: "#1D9E75",
    summary: "KMZ map overlay, site pins, GPS photo markers, route redlines.",
    chips: ["KMZ Map", "Site Pins", "GPS Photos", "Redlines"],
    preview: "map",
  },
  {
    key: "upload",
    title: "Upload Center",
    icon: `<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M10 13V4M6 8l4-4 4 4"/><path d="M4 14v2a1 1 0 001 1h10a1 1 0 001-1v-2"/></svg>`,
    accent: "#00bcd4",
    summary: "Bring in photos, PDFs, invoices, KMZ maps, spreadsheets, and ZIP packages.",
    chips: ["Drag & Drop", "File Detection", "Route to Workflow", "Review Before Import"],
    preview: "upload",
  },
];

window.PRESENTATION_REDUCES = [
  { icon: "📋", label: "Paperwork", desc: "Replace handwritten sheets with structured digital records." },
  { icon: "📷", label: "Lost Photos", desc: "GPS-tagged field photos attached directly to job records." },
  { icon: "💬", label: "Buried Text Messages", desc: "Work notes, issues, and updates live in the platform, not in texts." },
  { icon: "🔁", label: "Repeated Office Entry", desc: "Field entries flow into billing and reports automatically." },
  { icon: "📍", label: "Missing GPS Proof", desc: "Every photo, note, and completion carries a GPS timestamp." },
  { icon: "🧾", label: "Invoice Confusion", desc: "Compare field work, photos, and invoice lines in one place." },
  { icon: "📦", label: "Material Tracking Gaps", desc: "Track what was ordered, received, and used against each job." },
  { icon: "📞", label: "Supervisor Follow-Up Calls", desc: "Supervisors see job status and proof records without calling crews." },
];

window.PRESENTATION_ORGANIZES = [
  { icon: "🏗️", label: "Jobs" },
  { icon: "🎫", label: "Tickets" },
  { icon: "📷", label: "Photos" },
  { icon: "🗺️", label: "Maps" },
  { icon: "✏️", label: "Redlines" },
  { icon: "📦", label: "Materials" },
  { icon: "🧾", label: "Invoices" },
  { icon: "⏱️", label: "Timesheets" },
  { icon: "📁", label: "Closeout Packages" },
  { icon: "🔄", label: "Company Task Flow" },
];
